test tf cloud

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -42,6 +42,8 @@
 #       with:
 #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
+
+
 name: 'Terraform'
 
 on:
@@ -54,7 +56,7 @@ jobs:
   terraform:
     name: 'Terraform'
     runs-on: ubuntu-latest
-    environment: dev
+    # environment: dev
 
     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
     defaults:
@@ -73,36 +75,46 @@ jobs:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
         terraform_wrapper: false
 
+    - name: Terraform Format
+      id: fmt
+      run: terraform fmt -check
+
     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
       run: terraform init
 
-    # Checks that all Terraform configuration files adhere to a canonical format
-    # - name: Terraform Format
-    #   run: terraform fmt -check
+    - name: Terraform Validate
+      id: validate
+      run: terraform validate -no-color
+
+    - name: Terraform Plan
+      id: plan
+      if: github.event_name == 'pull_request'
+      run: terraform plan -no-color
+      continue-on-error: true
 
     #  Execution and save plan to json file
-    - name: Terraform Plan
-      if: github.event_name == 'pull_request'
-      run: |
-        terraform plan --out tfplan.binary
-        terraform show -json tfplan.binary > tfplan.json
-      env:
-          TF_VAR_credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
+    # - name: Terraform Plan
+    #   if: github.event_name == 'pull_request'
+    #   run: |
+    #     terraform plan --out tfplan.binary
+    #     terraform show -json tfplan.binary > tfplan.json
+    #   env:
+    #       TF_VAR_credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
 
-    # Install the lastest conftest for policy check
-    - name: Setup Conftest
-      run: |
-        wget https://github.com/open-policy-agent/conftest/releases/download/v0.25.0/conftest_0.25.0_Linux_x86_64.tar.gz
-        tar xzf conftest_0.25.0_Linux_x86_64.tar.gz
-        sudo mv conftest /usr/local/bin
-        source ~/.bashrc
-        conftest -v
+    # # Install the lastest conftest for policy check
+    # - name: Setup Conftest
+    #   run: |
+    #     wget https://github.com/open-policy-agent/conftest/releases/download/v0.25.0/conftest_0.25.0_Linux_x86_64.tar.gz
+    #     tar xzf conftest_0.25.0_Linux_x86_64.tar.gz
+    #     sudo mv conftest /usr/local/bin
+    #     source ~/.bashrc
+    #     conftest -v
     
-    - name: Conftest policy check
-      id: conftest
-      run: conftest test tfplan.json -p policy/ --all-namespaces -o table --no-fail
-      continue-on-error: true
+    # - name: Conftest policy check
+    #   id: conftest
+    #   run: conftest test tfplan.json -p policy/ --all-namespaces -o table --no-fail
+    #   continue-on-error: true
 
     # - name: Policy check result if pass
     #   run: ./policy-check.sh
@@ -110,15 +122,50 @@ jobs:
     - name: Update Pull Request
       uses: actions/github-script@0.9.0
       if: github.event_name == 'pull_request'
+      env:
+        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         script: |
-          ### Conftest test result
-          ```
-          ${{ steps.conftest.outputs.result }}
-          ```
+          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+
+          <details><summary>Show Plan</summary>
+
+          \`\`\`\n
+          ${process.env.PLAN}
+          \`\`\`
+
+          </details>
 
           *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+
+          github.issues.createComment({
+            issue_number: context.issue.number,
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            body: output
+          })
+          
+    - name: Terraform Plan Status
+      if: steps.plan.outcome == 'failure'
+      run: exit 1
+
+
+    # - name: Output to PR
+    #   uses: actions/github-script@0.9.0
+    #   if: github.event_name == 'pull_request'
+    #   with:
+    #     github-token: ${{ secrets.GITHUB_TOKEN }}
+    #     script: |
+    #       ### Conftest test result
+    #       ```
+    #       ${{ steps.conftest.outputs.result }}
+    #       ```
+
+    #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
       
       # On push to main, build or change infrastructure according to Terraform configuration files
       # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
